# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).

# -- Spree
unless Spree::Country.find_by_name 'United Kingdom'
  puts "[db:seed] Seeding Spree"
  Spree::Core::Engine.load_seed if defined?(Spree::Core)
  Spree::Auth::Engine.load_seed if defined?(Spree::Auth)
end

# -- States
unless Spree::State.find_by_name 'York'
  country = Spree::Country.find_by_name('United Kingdom')
  
  puts "[db:seed] Seeding states"

  [
    ['Aberdeen City', 'AbC'],
    ['Aberdeenshire', 'AbS'],
    ['Angus', 'Ang'],
    ['Antrim', 'Ant'],
    ['Ards', 'Ard'],
    ['Argyll and Bute', 'Arg'],
    ['Ballymena', 'Bme'],
    ['Ballymoney', 'Bmy'],
    ['Banbridge', 'Ban'],
    ['Barnsley', 'Bar'],
    ['Bath and North East Somerset', 'Bat'],
    ['Bedford Borough', 'Bed'],
    ['Belfast', 'Bel'],
    ['Birmingham', 'Bir'],
    ['Blackburn with Darwen', 'BwD'],
    ['Blackpool', 'Bla'],
    ['Blaenau Gwent', 'BGw'],
    ['Bolton', 'Bol'],
    ['Bournemouth', 'Bou'],
    ['Bracknell Forest', 'Bra'],
    ['Bradford', 'Bra'],
    ['Bridgend', 'Bri'],
    ['Brighton and Hove', 'Bri'],
    ['Buckingham', 'Buc'],
    ['Buckinghamshire', 'Buc'],
    ['Bury', 'Bur'],
    ['Caerphilly', 'Cae'],
    ['Calderdale', 'Cal'],
    ['Cambridgeshire', 'Cam'],
    ['Cardiff', 'Car'],
    ['Carmarthenshire', 'Cms'],
    ['Carrickfergus', 'Cfg'],
    ['Castlereagh', 'Cas'],
    ['Central Bedfordshire', 'Cen'],
    ['Ceredigion', 'Cer'],
    ['Cheshire East', 'ChE'],
    ['Cheshire West and Chester', 'CWC'],
    ['City of Bristol', 'CBr'],
    ['City of Edinburgh', 'CEd'],
    ['City of Kingston-upon-Hull', 'CKH'],
    ['City of London', 'CLn'],
    ['Clackmannanshire', 'Cla'],
    ['Coleraine', 'Col'],
    ['Conwy', 'Con'],
    ['Cookstown', 'Coo'],
    ['Cornwall', 'Cor'],
    ['County Armagh', 'CAr'],
    ['County Durham', 'CDu'],
    ['County Fermanagh', 'CFe'],
    ['County of Herefordshire', 'CHe'],
    ['Coventry', 'Cov'],
    ['Craigavon', 'Cra'],
    ['Cumbria', 'Cum'],
    ['Darlington', 'Dar'],
    ['Denbighshire', 'Den'],
    ['Derby', 'Der'],
    ['Derbyshire', 'Drs'],
    ['Derry', 'Der'],
    ['Devon', 'Dev'],
    ['Doncaster', 'Don'],
    ['Dorset', 'Dor'],
    ['Down', 'Dow'],
    ['Dudley', 'Dud'],
    ['Dumfries and Galloway', 'DaG'],
    ['Dundee City', 'Dun'],
    ['Dungannon', 'Dgn'],
    ['East Ayrshire', 'EAy'],
    ['East Dunbartonshire', 'EDu'],
    ['East Lothian', 'ELo'],
    ['East Renfrewshire', 'ERe'],
    ['East Riding of Yorkshire', 'ERY'],
    ['East Sussex', 'ESu'],
    ['Eilean Siar', 'Eil'],
    ['Essex', 'Ess'],
    ['Falkirk', 'Fal'],
    ['Fife', 'Fif'],
    ['Flintshire', 'Fli'],
    ['Gateshead', 'Gat'],
    ['Glasgow City', 'Gla'],
    ['Gloucestershire', 'Glo'],
    ['Greater London', 'GLn'],
    ['Greater Manchester', 'GMn'],
    ['Guernsey', 'Gue'],
    ['Gwynedd', 'Gwy'],
    ['Halton', 'Hal'],
    ['Hampshire', 'Ham'],
    ['Hartlepool', 'Har'],
    ['Hertford', 'Her'],
    ['Hertfordshire', 'Hfs'],
    ['Highland', 'Hig'],
    ['Isle of Man', 'IOM'],
    ['Inverclyde', 'Ivc'],
    ['Inverness-shire', 'Inv'],
    ['Isle Of Wight', 'IWi'],
    ['Isle of Anglesey', 'IAn'],
    ['Isles Of Scilly', 'ISc'],
    ['Jersey', 'Jer'],
    ['Kent', 'Ken'],
    ['Kirklees', 'Kir'],
    ['Knowsley', 'Kno'],
    ['Lancashire', 'Lan'],
    ['Larne', 'Lar'],
    ['Leeds', 'Lee'],
    ['Leicester', 'Lei'],
    ['Leicestershire', 'Lcs'],
    ['Limavady', 'Lim'],
    ['Lincolnshire', 'Lin'],
    ['Lisburn', 'Lis'],
    ['Liverpool', 'Liv'],
    ['London', 'Lon'],
    ['Luton', 'Lut'],
    ['Magherafelt', 'Mag'],
    ['Medway', 'Med'],
    ['Merthyr Tydfil', 'Mer'],
    ['Middlesbrough', 'Mdb'],
    ['Midlothian', 'Mdl'],
    ['Milton Keynes', 'Mil'],
    ['Monmouthshire', 'Mon'],
    ['Moray', 'Mor'],
    ['Moyle', 'Moy'],
    ['Neath Port Talbot', 'Nea'],
    ['Newcastle Upon Tyne', 'Nwc'],
    ['Newport', 'Npt'],
    ['Newry and Mourne', 'NaM'],
    ['Newtownabbey', 'Nta'],
    ['Norfolk', 'Nor'],
    ['North Ayrshire', 'NAy'],
    ['North Down', 'NDo'],
    ['North East Lincolnshire', 'NEL'],
    ['North Lanarkshire', 'NLa'],
    ['North Lincolnshire', 'NLi'],
    ['North Somerset', 'NSo'],
    ['North Tyneside', 'Nor'],
    ['North Yorkshire', 'NYo'],
    ['Northamptonshire', 'Nts'],
    ['Northumberland', 'Ntb'],
    ['Nottingham', 'Not'],
    ['Nottinghamshire', 'Not'],
    ['Oldham', 'Old'],
    ['Omagh', 'Oma'],
    ['Orkney Islands', 'Ork'],
    ['Oxfordshire', 'Oxf'],
    ['Pembrokeshire', 'Pem'],
    ['Perth and Kinross', 'Per'],
    ['Peterborough', 'Pet'],
    ['Plymouth', 'Ply'],
    ['Poole', 'Poo'],
    ['Portsmouth', 'Por'],
    ['Powys', 'Pow'],
    ['Reading', 'Rea'],
    ['Redcar and Cleveland', 'Red'],
    ['Renfrewshire', 'Ren'],
    ['Rhondda Cynon Taff', 'Rho'],
    ['Rochdale', 'Roc'],
    ['Rotherham', 'Rot'],
    ['Rutland', 'Rut'],
    ['Salford', 'Sal'],
    ['Sandwell', 'San'],
    ['Sefton', 'Sef'],
    ['Sheffield', 'She'],
    ['Shetland Islands', 'SIs'],
    ['Shropshire', 'Shr'],
    ['Slough', 'Slo'],
    ['Solihull', 'Sol'],
    ['Somerset', 'Som'],
    ['South Ayrshire', 'SAy'],
    ['South Gloucestershire', 'SGl'],
    ['South Lanarkshire', 'SLan'],
    ['South Tyneside', 'STy'],
    ['Southampton', 'Sou'],
    ['Southend-on-Sea', 'SSe'],
    ['St Helens', 'StH'],
    ['Staffordshire', 'Sta'],
    ['Stirling', 'Sti'],
    ['Stockport', 'Sto'],
    ['Stockton-on-Tees', 'STe'],
    ['Stoke-on-Trent', 'STr'],
    ['Strabane', 'Str'],
    ['Suffolk', 'Suf'],
    ['Sunderland', 'Sun'],
    ['Surrey', 'Sur'],
    ['Swansea', 'Swa'],
    ['Swindon', 'Swi'],
    ['Tameside', 'Tam'],
    ['Telford and Wrekin', 'Tel'],
    ['The Scottish Borders', 'TSB'],
    ['The Vale of Glamorgan', 'TVG'],
    ['Thurrock', 'Thu'],
    ['Torbay', 'Tor'],
    ['Torfaen', 'Trf'],
    ['Trafford', 'Tra'],
    ['Wakefield', 'Wak'],
    ['Walsall', 'Wal'],
    ['Warrington', 'War'],
    ['Warwickshire', 'Wrk'],
    ['West Berkshire', 'WBe'],
    ['West Dunbartonshire', 'WDu'],
    ['West Lothian', 'WLo'],
    ['West Sussex', 'WSu'],
    ['Wigan', 'Wig'],
    ['Wiltshire', 'Wil'],
    ['Windsor and Maidenhead', 'Win'],
    ['Wirral', 'Wir'],
    ['Wokingham', 'Wok'],
    ['Wolverhampton', 'Wol'],
    ['Worcester', 'Wor'],
    ['Worcestershire', 'Wrs'],
    ['Wrexham', 'Wre'],
    ['York', 'Yor'],
  ].each do |state|
    Spree::State.create!({"name"=>state[0], "abbr"=>state[1], :country=>country}, :without_protection => true)
  end
end

# -- Landing page images
unless LandingPageImage.find_by_photo_file_name("potatoes.jpg")
  LandingPageImage.create photo: File.open(File.join(Rails.root, "lib", "seed_data", "carrots.jpg"))
  LandingPageImage.create photo: File.open(File.join(Rails.root, "lib", "seed_data", "tomatoes.jpg"))
  LandingPageImage.create photo: File.open(File.join(Rails.root, "lib", "seed_data", "potatoes.jpg"))
end

# -- Seeding suburbs
require_relative './suburb_seeds'
SuburbSeeder.seed_suburbs unless Suburb.find_by_name("Toab")
